FROM alpine:edge as builder

COPY ./mailfilter /mailfilter

RUN apk add --no-cache \
        build-base \
        bison \
        flex \
        flex-dev \
        openssl \
        openssl-dev \
        autoconf \
        automake \
 && cd /mailfilter \
 && ./autogen.sh \
 && make \
 && make install

FROM alpine:edge

RUN apk add --no-cache \
        libstdc++ \
        openssl \
        fetchmail

COPY --from=builder /usr/local/bin/mailfilter /usr/local/bin/

USER fetchmail

CMD /usr/bin/fetchmail
