# This is a basic workflow that is manually triggered

name: Docker build postfix multiarch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

env:
  TEST: postfix:test

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Get Postfix version used in image tags
        run: |
          docker build -t $TEST .
          VERSION=$(docker run $TEST postconf mail_version | sed 's/mail_version = //')
          image_name=ghcr.io/${{ github.repository_owner }}/postfix
          echo "tags=${image_name}:${VERSION},${image_name}:latest" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ghcr.io/${{ github.repository_owner }}/postfix:${{ env.VERSION }}
        run: echo "${{ env.tags }}"
      
      - name: Build and push postfix ${{ env.VERSION }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: ${{ env.tags }}
